#include "REGISTRY.h"
#include "../../RES/MEM/MEM.h"

SETPOINTS_s SETPOINTS;
PROCESSVALUES_s PROCESSVALUES;
PARAMETERS_s PARAMETERS;

void REGISTRY_INIT(void)
{
    /* initialize the setpoints */
    SETPOINTS.ENABLE = 0;
    SETPOINTS.TARGET_TORQUE = 0;
    SETPOINTS.TARGET_FREQUENCY = 0;
    SETPOINTS.REVERSAL = 0;
    SETPOINTS.ENABLE_CURRENT_OVERDRIVE = 0;
    SETPOINTS.ENABLE_FREQUENCY_OVERDRIVE = 0;
    SETPOINTS.ENABLE_PROGMODE = 0;
    SETPOINTS.TRIGGER_PARAMETER_SAVE = 0;
    SETPOINTS.TRIGGER_UF_CALCULATION = 0;

    /* initialize the process values */
    PROCESSVALUES.DCBUS_VOLTAGE = 0;
    PROCESSVALUES.DCBUS_CURRENT = 0;
    PROCESSVALUES.MOTOR_VOLTAGE = 0;
    PROCESSVALUES.MOTOR_CURRENT = 0;
    PROCESSVALUES.MOTOR_FREQUENCY = 0;
    PROCESSVALUES.MOTOR_POWER = 0;
    PROCESSVALUES.SYSTEM_ERROR = 0;

    /* initialize the parameters before non-volatile memory read */
    PARAMETERS.MODBUS_ADDRESS = 0;
    PARAMETERS.PWM_FREQUENCY = 0;
    PARAMETERS.PWM_DEADTIME = 0;
    PARAMETERS.PWM_DEADTIME_PRESCALING = 0;
    PARAMETERS.DCBUS_NOMINAL_VOLTAGE = 0;
    PARAMETERS.MOTOR_NOMINAL_VOLTAGE = 0;
    PARAMETERS.MOTOR_MINIMAL_VOLTAGE = 0;
    PARAMETERS.MOTOR_NOMINAL_FREQUENCY = 0;
    PARAMETERS.MOTOR_VOLTBOOST_FREQUENCY = 0;
    PARAMETERS.MOTOR_NOMINAL_FWD_CURRENT = 0;
    PARAMETERS.MOTOR_NOMINAL_REV_CURRENT = 0;
    PARAMETERS.MOTOR_OVERDRIVE_FWD_CURRENT = 0;
    PARAMETERS.MOTOR_OVERDRIVE_REV_CURRENT = 0;
    PARAMETERS.CONTROLLER_NOMINAL_FREQUENCY = 0;
    PARAMETERS.CONTROLLER_OVERDRIVE_FREQUENCY = 0;
    PARAMETERS.CONTROLLER_PROPORTIONAL_FACTOR = 0;
    PARAMETERS.CONTROLLER_INTEGRAL_FACTOR = 0;
    PARAMETERS.CONTROLLER_SAMPLETIME = 0;
    PARAMETERS.CONTROLLER_ENABLE_TIMEOUT = 0;
    PARAMETERS.CONTROLLER_OVERDRIVE_TIMEOUT = 0;
    PARAMETERS.CONTROLLER_OVERDRIVE_COOLDOWN = 0;

    REGISTRY_SETSTATUS("[ INFO ] SYSTEM INITIALIZING", 28);

    if(REGISTRY_POPEEMEM() == -1)
    {
        PROCESSVALUES.SYSTEM_ERROR = 1;
    }

    else
    {
        PROCESSVALUES.SYSTEM_ERROR = 0;
        REGISTRY_SETSTATUS("[ INFO ] SYSTEM STOP", 20);
    }
}

void REGISTRY_SETSTATUS(char *msg, uint8_t size)
{
    uint8_t counter = 0;

    if(size > 47)
    {
        return;
    }

    for(counter = 1; counter <= size; counter++)
    {
        PROCESSVALUES.SYSTEM_STATUS[counter] = msg[counter - 1];
    }

    PROCESSVALUES.SYSTEM_STATUS[counter] = '\n';
    PROCESSVALUES.SYSTEM_STATUS[0] = size + 1;
}


void REGISTRY_PUSHEEMEM(void)
{
    MEM_WRITE(0, &PARAMETERS, sizeof(PARAMETERS_s));

    /* trigger the watchdog to restart the program */
    while(1);
}

int8_t REGISTRY_POPEEMEM(void)
{
    return MEM_READ(0, &PARAMETERS, sizeof(PARAMETERS_s));
}
