#include "REGISTRY.h"

SETPOINTS_s SETPOINTS;
MEASUREMENTS_s MEASUREMENTS;
PARAMETERS_s PARAMETERS;

void REGISTRY_INIT(void)
{
    SETPOINTS.TARGET_FREQUENCY = 0;
    SETPOINTS.RELATIVE_TORQUE = 0;
    SETPOINTS.REVERSAL = 0;
    SETPOINTS.ENABLE_FREQUENCY_OVERDRIVE = 0;
    SETPOINTS.ENABLE_CURRENT_OVERDRIVE = 0;
    SETPOINTS.ENABLE_PROGMODE = 0;

    MEASUREMENTS.LINE_VOLTAGE = 0;
    MEASUREMENTS.LINE_CURRENT = 0;
    MEASUREMENTS.BUS_VOLTGE = 0;
    MEASUREMENTS.BUS_CURRENT = 0;
    MEASUREMENTS.OUTPUT_FREQUENCY = 0;
    MEASUREMENTS.OUTPUT_POWER = 0;
    MEASUREMENTS.TEMPERATURE1 = 0;
    MEASUREMENTS.TEMPERATURE2 = 0;
}
